DARWIN: Specify 'int' return type for PFI
In recent versions of Xcode (around the release of macOS 14), clang
yields this error (previously a  warning):

  src/afs/DARWIN/osi_vfsops.c:534:11: error: type specifier missing,
     defaults to 'int'; ISO C99 and later do not support implicit int
     [-Wimplicit-int]
   typedef (*PFI) ();

Explicitly specify 'int' for PFI.

[mvitale: commit message details; use 'int' rather than 'void' to match
corresponding XNU typedef]

Reviewed-on: https://gerrit.openafs.org/16139
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
(cherry picked from commit 3beeb7a6806066e8c07ebf9f9f1fbe407161fb51)

Change-Id: Ic83f516e42f200202b4a14ac6105905787eaf634