FBSD: Cast afs_symlink target to char*
FreeBSD commit 1493c2ee62b8cbd8dbe70670b9108b4b9c36e032 (Make
vop_symlink take a const target path.) changed the 'target' argument
of vop_symlink to be a 'const char*' (from 'char*'). This causes a
warning:

    .../src/afs/FBSD/osi_vnodeops.c:1099:44: error: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
            afs_symlink(VTOAFS(dvp), name, ap->a_vap, ap->a_target, NULL,
                                                      ^~~~~~~~~~~~
    .../src/afs/afs_prototypes.h:1328:37: note: passing argument to parameter 'atargetName' here
                           struct vattr *attrs, char *atargetName,

Just cast to 'char*' explicitly to get rid of the warning.

Ideally we would change afs_symlink() to accept a 'const char*', but
that involves a lot of changes to cross-platform code; keep things
simple for now.

Reviewed-on: https://gerrit.openafs.org/15171
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit ad7a5ba33399f47c781cb5b177bab1e578eaca23)

Change-Id: I9d277c96918c93237283db4a549d9b638879dfb5