DARWIN: Define return type for getinode()
In recent versions of Xcode (around the release of macOS 14), clang now
flags the lack of a return type for these functions as errors instead of
warnings:

  src/afs/DARWIN/osi_inode.c:30:1:
    error: type specifier missing, defaults to 'int'; ISO C99 and
    later do not support implicit int [-Wimplicit-int]

   getinode(fs, dev, inode, vpp, perror)
   ^

  src/afs/DARWIN/osi_inode.c:60:1:
    error: type specifier missing, defaults to 'int'; ISO C99 and
    later do not support implicit int [-Wimplicit-int]

   igetinode(vfsp, dev, inode, vpp, va, perror)
   ^

Eliminate the errors by explicitly declaring each function as return
type 'int'.

[mvitale: commit message details]

Reviewed-on: https://gerrit.openafs.org/16137
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
(cherry picked from commit 6e0b549fd54ab3815d65425330b9bb66fbed3626)

Change-Id: I18d6054a51f31f53b998b254d50d469b463efc1c