DARWIN: Skip NULL func ptrs in osi_vnodeops.c
In recent versions of Xcode (around the release of macOS 14), clang now
reports these former warnings as errors:

    src/afs/DARWIN/osi_vnodeops.c:163:12:
        error: incompatible function pointer types initializing
        'int (*)(void*)' with an expression of type 'void (*)()'
        [-Wincompatible-function-pointer-types]

     {NULL, (void (*)())NULL}
            ^~~~~~~~~~~~~~~~

    src/afs/DARWIN/osi_vnodeops.c:206:12:
        error: incompatible function pointer types initializing
        'int (*)(void*)' with an expression of type 'void (*)()'
        [-Wincompatible-function-pointer-types]

     {NULL, (void (*)())NULL}
            ^~~~~~~~~~~~~~~~

To avoid these errors, simply do not specify the function pointer, and
let the rest of the struct value get filled in with zeroes.

Also specify a return type for afs_vop_pathconf(), to avoid this error
(which clang formerly flagged as a warning):

    src/afs/DARWIN/osi_vnodeops.c:1841:1:
        error: type specifier missing, defaults to 'int'; ISO C99 and
        later do not support implicit int [-Wimplicit-int]

     afs_vop_pathconf(ap)
     ^

[mvitale, adeason: commit message details]

Reviewed-on: https://gerrit.openafs.org/16138
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
(cherry picked from commit 3f64facc10e34145f316decf19e24665682f8db9)

Change-Id: Id0694a0559bf9208e2bf29b5f2aaeb03ff5d0097