volser: Avoid uninitialized 'code' in CheckVolume
The CheckVolume() function can potentially use the 'code' variable
before it is initialized if the volume being checked has an invalid or
unknown volume type. This has been the case since commit 663be53c18
(volser: Split CheckVolume into RW/RO/BK functions); before that
commit, an invalid volume type would cause us to skip most of our
volumes checks in CheckVolume().

Add a check to return EINVAL and print an error message to avoid this
case. This fixes the following compiler warning seen on GCC 4.4.7:

    vsprocs.c: In function 'CheckVolume':
    vsprocs.c:5859: error: 'code' may be used uninitialized in this function [-Wuninitialized]

Reviewed-on: https://gerrit.openafs.org/16364
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit b1d48cbf9187a454d971cd4e9a87295f4edf2647)

Change-Id: I7b19f5306c2d91ce180b4e20181c90073095fa36