DARWIN: Allow use of CAST_USER_ADDR_T again
CAST_USER_ADDR_T is a Darwin-supplied typedef to assist in address
handling between userspace and kernelspace.

Commit 81099c479e14 (macos 10.6 64 bit support) disabled AFS_COPYIN's
use of CAST_USER_ADDR_T in AFS_DARWIN100_ENV (10.6 Snow Leopard) and
higher to prevent issues caused by that release's support for mixed
32-bit or 64-bit userspace and kernelspace. Although this could generate
type-mismatch warnings for AFS_COPYIN, they were ignored.

However, in recent versions of Xcode (around the release of macOS 14),
this warning is now reported as an error:

  src/afs/afs_syscall.c:373:5: error: incompatible pointer to integer
                         conversion passing 'caddr_t' (aka 'char *') to
                         parameter of type 'user_addr_t' (aka 'unsigned long long')
	                 [-Wint-conversion]
     AFS_COPYIN(cmarg, (caddr_t) dst, sizeof *dst, code);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

To eliminate this error, reinstate use of CAST_USER_ADDR_T for modern
macOS releases (AFS_DARWIN190_ENV 10.15 Catalina and up) which support
only 64-bit userspace and kernelspace.

Thanks to Ganesh Chaudhari for reporting the issue and providing a
preliminary fix.

Reviewed-on: https://gerrit.openafs.org/16142
Reviewed-by: Mark Vitale <mvitale@sinenomine.net>
Reviewed-by: Michael Meffie <mmeffie@sinenomine.net>
Reviewed-by: Marcio Brito Barbosa <mbarbosa@sinenomine.net>
Tested-by: BuildBot <buildbot@rampaginggeek.com>
Reviewed-by: Cheyenne Wills <cwills@sinenomine.net>
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit bac7955a2e892dce1e22629b5858641e7a32bf25)

Change-Id: If412eed17f0ac688dba8be569ebc389ee55cda00