DARWIN: Correct function signature of afs_mount
Since commit bb33cbb6eb15 (macos-rollup-20051013) the function signature
for afs_mount has been incorrect, resulting in a warning.

In recent versions of Xcode (around the release of macOS 14), this is
now flagged as an error:

  /src/afs/DARWIN/osi_vfsops.c:607:4: error: incompatible function
                  pointer types initializing 'int (*)(struct mount *, vnode_t,
                  user_addr_t, vfs_context_t)' (aka 'int (*)(struct mount *,
                  struct vnode*, unsigned long long, struct vfs_context *)')
                  with an expression of type 'int (struct mount *, vnode_t *,
                  user_addr_t, vfs_context_t)' (aka 'int (struct mount *,
                  struct vnode **, unsigned long long, struct vfs_context *)')
                  [-Wincompatible-function-pointer-types]
   afs_mount,
   ^~~~~~~~~

To eliminate the build error, correct the function signature by
declaring 'devvp' as a vnode_t, not a vnode_t*. (The devvp argument is
not used in afs_mount(), so changing the type has no impact on the rest
of the function.)

[mvitale: commit message details]

Reviewed-on: https://gerrit.openafs.org/16140
Reviewed-by: Andrew Deason <adeason@sinenomine.net>
Tested-by: Andrew Deason <adeason@sinenomine.net>
(cherry picked from commit 41bf672ebc79093d278c75bb8b41659820b2f616)

Change-Id: Ie03e9bb133f5aab8d96703583328562765df36be